# Generated by Django 5.2.12 on 2026-03-29 16:53

import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectimage",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=projects.models.project_image_path
            ),
        ),
    ]
