# Generated by Django 5.2.12 on 2026-03-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_alter_projectimage_image_alter_stepimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectimage",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="stepimage",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
