# Generated by Django 5.2.12 on 2026-04-15 18:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniatures', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='element',
            options={'verbose_name': 'Element', 'verbose_name_plural': 'Elements'},
        ),
        migrations.AlterModelOptions(
            name='miniature',
            options={'verbose_name': 'Miniature', 'verbose_name_plural': 'Miniatures'},
        ),
        migrations.CreateModel(
            name='MiniaturePhoto',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='miniature_photos/', verbose_name='Photo')),
                ('is_cover', models.BooleanField(default=False, verbose_name='Is Cover Photo')),
                ('miniature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='miniatures.miniature', verbose_name='Miniature')),
            ],
            options={
                'verbose_name': 'Miniature Photo',
                'verbose_name_plural': 'Miniature Photos',
            },
        ),
    ]
